trigger:
- dev

pool:
   vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "Running make dist"
    make dist
    ls dist
    docker login -u $(DOCKER_HUB_USER) -p $(DOCKER_PAT)
    make buildswitch-dev
    make switch-push-dev
  displayName: 'Building and pushing dev image'


