trigger:
- feature/dokerize

pool:
   vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: |
    echo "Running make dist"
    make dist
    ls dist
    make buildswitch-dev
    make switch-push-dev
  displayName: 'Run make dist'


