FROM thedarkside362/vocodiaswitchbase:1.0

USER vocodia-dev

COPY dist/ ${DEPLOY_DIR}/find-links/

USER root
RUN usermod -aG root vocodia-dev && \
    mkdir -p ${DEPLOY_DIR}/find-links/ && \
    cd ${DEPLOY_DIR}/find-links/ && \
    ls -ld /var/log && \
    ls -lha ${DEPLOY_DIR}/find-links/ && \
    ${DEPLOY_DIR}/bin/pip install ${DEPLOY_DIR}/find-links/vocodiaswitchservices-1.0.0.tar.gz

USER vocodia-dev
